### ISSUE TITLE
not getting release artefact when running actions on fork 

### ISSUE THREAD

**Issue by stevenj2019** [BusKill/buskill-app#18]
When running GitHub Actions on forked version of repo not getting build release asset. 

https://github.com/stevenj2019/buskill-app/runs/1730209270?check_suite_focus=true

Link to the build in question. 

on step "Upload Release Asset" the URL provided links to BusKill's GitHub Repo as oppose to the repo the build was created on

**Comment by maltfield** [comment]
Thanks for the report :) let's fix this!

First, here's the docs on github actions for the list of available environment variables that could be used to make this more robust:
 * https://docs.github.com/en/actions/reference/environment-variables

Probably what we need is GITHUB_REPOSITORY = `buskill/buskill-app` or `stevenj2019/buskill-app`

**Comment by maltfield** [comment]
@stevenj2019 I've pushed a fix up to `dev` can you please pull it from upstream into your repo, merge it into your branch, and confirm that it can now create your more-reasonably-sized releases directly in your fork on `git push`?

 * https://github.com/BusKill/buskill-app/commit/7e53bb957c48766327a3c95c71b96c32337a3dd0

**Comment by maltfield** [comment]
@stevenj2019 I've pushed a fix up to `dev` can you please pull it from upstream into your repo, merge it into your branch, and confirm that it can now create your more-reasonably-sized releases directly in your fork on `git push`?

 * https://github.com/BusKill/buskill-app/commit/7e53bb957c48766327a3c95c71b96c32337a3dd0

**Comment by stevenj2019** [comment]
fixed :) 

Thank you @maltfield
