### ISSUE TITLE
Windows Build error on fork

### ISSUE THREAD

**Issue by stevenj2019** [BusKill/buskill-app#19]
https://github.com/stevenj2019/buskill-app/actions/runs/524262719

Windows Build error occurs. Seems to be trying to push binary to BusKills Repo instead of branch. 

Many Thanks :)

**Comment by maltfield** [comment]
This should be fixed in the dev branch

 * https://github.com/BusKill/buskill-app/commit/7e53bb957c48766327a3c95c71b96c32337a3dd0#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721
