### ISSUE TITLE
CLI on Windows? Documentation might need updating if it isn't broken entirely

### ISSUE THREAD

**Issue by wolfgirl42** [BusKill/buskill-app#44]
I have made multiple attempts to run the CLI on Windows (attempting to use soft shutdown trigger and possibly custom triggers) and it just launches the GUI program. If the CLI is usable on Windows, there is definitely a lack of documentation as to how to achieve that.

Is the CLI intended to work on windows, or is that on the future roadmap?

**To Reproduce**
1. Open CMD at the Buskill install dir
2. run `buskill.exe --list-triggers` which should invoke the CLI
3. (nothing happens)
4. run `buskill.exe` (no args) - GUI opens

Also had a quick go at running it via cygwin python but the gnupg package doesn't support cygwin. Might be a workaround somewhere but currently lacking the time/spoons.

**Expected behavior**
CLI working on Windows

**Versions (please complete the following information):**
 - OS: Windows 10
 - BusKill: v 0.6.0

Happy to do any further testing or run any experimental builds.

**Comment by maltfield** [comment]
@wolfgirl42 please see the documentation on how to use the CLI in Windows?

 * https://docs.buskill.in/buskill-app/en/stable/software_usr/cli.html

Quoting from the above link

> Due to a limitation in the Windows API, executables cannot be switched between CONSOLE and WINDOWS at runtime. This effectively means that buskill.exe can be executed from the CLI, but it won’t be interactive. For more info, see:
> 
>         https://github.com/BusKill/buskill-app/issues/21
> 
> As a simple workaround to launch the BusKill app in CLI mode, simply append | more to the command. For example, to arm the BusKill app from the CLI in the Windows Command Prompt:
> 
> C:\Users\user\Desktop\buskill-Windows\buskill>buskill.exe --arm | more

**Comment by maltfield** [comment]
See also https://github.com/BusKill/buskill-app/issues/21

**Comment by maltfield** [comment]
> Documentation might need updating if it isn't broken entirely #44

@wolfgirl42 if you didn't find the above documentation before, can you please let me know where you checked? What can we do to make this documentation easier to find? Where should we add links?

**Comment by maltfield** [comment]
Closing as I believe the above-linked documentation resolves this. Please re-open if there's anything more we can do.
