### ISSUE TITLE
Mastodon PGP key fingerprint doesn't match the release signing key

### ISSUE THREAD

**Issue by fmarier** [BusKill/buskill-app#54]
I found a link to the [Mastodon page](https://mastodon.social/@buskillin) on https://docs.buskill.in/buskill-app/en/stable/security/pgpkeys.html and noticed that the fingerprint listed there doesn't match any of the ones at the bottom of https://www.buskill.in/.

Is that normal? Is the Mastodon key supposed to be a different one?

**Comment by maltfield** [comment]
Thanks for catching this!

The PGP fingerprint on Mastodon was our original 3072-bit RSA key (I don't think this key was ever actually used before it was replaced)

```
pub   rsa3072/0x7881A036F21C15F8 2020-02-11 [SC] [expires: 2025-02-09]
      Key fingerprint = 053F B303 D09B D338 A95C  A993 7881 A036 F21C 15F8
uid                   [ultimate] BusKill Releases Signing Key 2020.02 <releases@buskill.in>
sub   rsa3072/0x13C75197B26F4AF1 2020-02-11 [E] [expires: 2025-02-09]
```

The above key was replaced in 2020-07 by a 4096-bit key:

```
pub   rsa4096/0x4AE21E1936CE786A 2020-07-07 [SC] [expires: 2025-07-06]
      Key fingerprint = E0AF FF57 DC00 FBE0 5635  8761 4AE2 1E19 36CE 786A
uid                   [  full  ] BusKill Releases Signing Key 2020.07 <releases@buskill.in>
sub   rsa4096/0xF9C0AEBD60002557 2020-07-07 [E] [expires: 2025-07-06]
sub   rsa4096/0x68B8BCB0C5023905 2020-07-07 [S] [expires: 2025-07-06]
```

I've updated the mastodon account. Thanks again for pointing this out! :)

 * https://mastodon.social/@BusKillin

On a related note, like so many others, we're still banned from twitter. I don't know why, and I guess we don't have as much power as all the journalists that were recently banned then unbanned *sigh*

 * https://twitter.com/buskillin

**Comment by maltfield** [comment]
See also:

 * https://github.com/BusKill/buskill-app/issues/5#issuecomment-655065236
