### ISSUE TITLE
Unusual interpreter in all Python files

### ISSUE THREAD

**Issue by fmarier** [BusKill/buskill-app#56]
All Python files that come from the Buskill project look like https://github.com/BusKill/buskill-app/blob/master/src/main.py#L1:

```
#!/usr/bin/env python3.7
```

In Debian, that interpreter is not available (only 3.9, 3.10 and 3.11 are in Debian unstable and therefore in the next stable release). I get the following warning when I build the package:
```
W: buskill: unusual-interpreter /usr/bin/python3.7 [usr/share/buskill/buskill_cli.py]
N: 
N:   This package contains a script for an interpreter that is not shipped in the package and is not known to Lintian. It is possible that
N:   there is a typo or the interpreter is not executable.
```

Now, this doesn't appear to be fatal, so I don't need to patch it, but I'm wondering why the shebang line is so specific. Normally I see this:
```
#!/usr/bin/env python3
```
and the OS has the appropriate symlink to make that point to the exact version that's installed.

Would that work with the AppImage/DMG/EXE too?

**Comment by maltfield** [comment]
Thanks for the report.

Yes, I'll try changing the shebang to `python3` and test that it doesn't break the 3 platform's builds.

**Comment by maltfield** [comment]
There's 5x relevant files here

```
user@buskill:~/sandbox/buskill-app/src$ grep -ir '/usr/bin/env python' *
buskill_cli.py:#!/usr/bin/env python3.7
buskill_gui.py:#!/usr/bin/env python3.7
main.py:#!/usr/bin/env python3.7
packages/buskill/root_child_mac.py:#!/usr/bin/env python3.7
packages/buskill/__init__.py:#!/usr/bin/env python3.7
user@buskill:~/sandbox/buskill-app/src$ 
```

**Comment by maltfield** [comment]
I've tested this in a new branch:

 * https://github.com/BusKill/buskill-app/tree/shebang_python3

**Comment by maltfield** [comment]
I confirmed that the lnux build executes after this change.

**Comment by maltfield** [comment]
I confirmed that the MacOS .dmg release linked-to above executes fine on MacOS after this change.

**Comment by maltfield** [comment]
I confirmed that the Windows 10 .zip release linked-to above executes fine on Windows 10 after this change.

**Comment by maltfield** [comment]
this has been merged into `dev`
