### ISSUE TITLE
Documentation to setup with Qubes OS

### ISSUE THREAD

**Issue by PowerPress** [BusKill/buskill-app#61]
Can you please document how to setup BusKill with Qubes OS?

**Comment by maltfield** [comment]
@PowerPress Does this have what you need?

 * https://www.buskill.in/qubes-os/

Or are you suggesting that it should be moved-to or linked-to in somewhere on https://docs.buskill.in?

**Comment by maltfield** [comment]
Unfortunately the feature requested in this issue is unclear and the OP hasn't responded for several months, so I'm going to close this.

@PowerPress if you can please supply more information on the issue and your desired fix, we can re-open and address your concerns.
