### ISSUE TITLE
[INFO] macOS: using third-party app EventScripts

### ISSUE THREAD

**Issue by JayBrown** [BusKill/buskill-app#67]
[INFO] only, but **question** below.

There's a nice app called **EventScripts** on the [Mac App Store](https://apps.apple.com/app/eventscripts/id525319418?l=en&mt=12) for $8, and one of the triggers is **USB device removed**, which you can use to execute any command you like in a (shell) script. For privileged commands like `sudo shutdown -h now` you'd need to call a secondary script that will run without your admin password, which you can define in `/private/etc/sudoers.d/$USER`, e.g. as 
```
$USER		ALL = (root) NOPASSWD: /Users/$USER/.local/bin/sudoers.sh
```
(Obviously you need to replace `$USER` with your real user name.) Just pass an argument like `sudo sudoers.sh shutdown`, and in the secondary script do something like `[[ $1 == "shutdown" ]] && shutdown -h now`

One downside, however, is that EventScripts will only give you the USB device's `_name`, but not `vendor_id`, `product_id` or `serial_num`. So if your dead-man-switch USB device is e.g. a widespread thumb drive with a `_name` like `STORE N GO`, you might encounter false positives down the road, so you'd probably need to use a drive from a more obscure vendor for your setup. (Or develop your own armed/disarmed solution.)

**Question**: does anyone know if there are "fake" USB-C data devices that just sit idle? (Those would imho be ideal for a dead man switch.) EDIT: a cheap FIDO security key would probably be a good choice.

**Comment by maltfield** [comment]
@JayBrown thanks for the ticket. Is there any reason you'd use EventScripts over this BusKill app? The latest version does support shutdown, so I'm a bit confused as to why it's mentioned.

> Question: does anyone know if there are "fake" USB-C data devices that just sit idle? (Those would imho be ideal for a dead man switch.) EDIT: a cheap FIDO security key would probably be a good choice.

I'm also not sure I understand the question. Is there any reason why not to use any off-the-shelf USB-C storage drive? Our documentation's [Bill of Materials](https://docs.buskill.in/buskill-app/en/stable/hardware_dev/bom.html) section links to one for $10 on amazon, but there's probably hundreds of alternatives.

 * https://docs.buskill.in/buskill-app/en/stable/hardware_dev/bom.html

**Comment by JayBrown** [comment]
It depends on what you want to do. If you just want to shut down, then you should probably use the BusKill app, because it does the one thing you need, does only that one thing, and does it well. But if (for example) you only want your user to be logged out, you could use something like EventScripts and run e.g. `killall WindowServer`. Other commands or solutions also come to mind like `pmset displaysleepnow`, a continuous klaxon over the speakers after `caffeinate -i &` etc. 

As for the device: the bill of materials actually lists a "Store 'n' Go" flash drive, and that's what I already covered above: these are widespread flash drives, and if (for example) you insert a colleague's or friend's StoreNGo flash drive to copy some files, and then remove the USB device, your computer would shut down, if it has the same device name as your kill device, and if you're using EventScripts. (That's why in this setup I thought it prudent to use a device that is not as widespread, i.e. has a device name that you are unlikely to encounter.)

**Comment by maltfield** [comment]
> you could use something like EventScripts and run e.g. killall WindowServer

Adding support for "auxiliary" triggers (ie execution of a user-defined, custom command) is on our roadmap, but it may be some time before the BusKill app supports it.

In the meantime, does MacOS not support udev like Linux? This was the original implementation of BusKill for Linux.

 * https://tech.michaelaltfield.net/2020/01/02/buskill-laptop-kill-cord-dead-man-switch/

If EventScripts is the closest thing MacOS has to udev, then that's good to know, thanks :)

> if (for example) you insert a colleague's or friend's StoreNGo flash drive to copy some files, and then remove the USB device, your computer would shut down

I guess the problem with udev/EventScripts is that you can't easily turn it off. That was one of the big changes with the GUI app (the arm/disarm button). Not sure of your use-case, but I only use the BusKill cable when doing specific kinds of work (eg handling of private keys), and if I'm doing that work (with BusKill armed) then I'm *not* going to be inserting someone else's hardware into my machine.

Unfortunately, I can't link to any obscure USB-C devices, but I'm sure if you buy a few cheap storage drives off aliexpress, you'll get some weird/unique device names ;) Alternatively, maybe add a method to "disarm" EventScripts when it's not needed, if that works for you?

I've always wondered if it were possible to rewrite a new `vendor_id` and other UIDs of the USB device. Please let us know if you have more info on that. If it were possible (if not for most devices, then perhaps on some hacker's USB device from adafruit or something) , I think that would be the most ideal solution.

**Comment by JayBrown** [comment]
I'm using EventScripts also as a security measure for unknown physical devices—currently only for fun, but it's working fine—, so I'll get notified on my iOS devices, if an unknown device is attached to the Mac while I'm afc, and the Mac then also takes photos with the iSight camera & stores them on the iCloud drive, and logs processes for any suspicious activity. For the use case when I'm present, I have a learning mode to scan new devices (vendor_id, product_id, serial_num) and approve them as trusted, which in principle I could remodel to override the (separate) kill switch, effectively creating an arm/disarm solution.

As for `udev`, I don't think that this is present on macOS.

I *assume* it should be possible to reflash a USB device, and I had actually looked for any info on that a couple of days ago, but didn't find anything. (In my case, for EventScripts, I would need to flash the `_name` to give it something individual/unique.)

**Comment by maltfield** [comment]
Closing this issue as I'm not sure there's any pending request. If incorrect, please let me know what is pending and we can re-open
