### ISSUE TITLE
Cannot update buskill-v0.6.0 from GUI using MacOS Sonoma 14.2.1

### ISSUE THREAD

**Issue by samxplogs** [BusKill/buskill-app#80]
1. run buskill-v0.6.0.
2. Click update feature in the GUI. 
3. Hit Check Updates

I face the following error message when running application from the desktop but behavior is the same if I run it from Applications:

Error invoking gpg: -6: dyld[1366]: Library not loaded: /usr/local/opt/libgcrypt/lib/libgcrypt.20.dylib
Referenced from: <C669489C-F22E-3798-9EE1-2B540BB0321A>
/Users/dh/Desktop/buskill-v0.6.0.app/Contents/Resources/gpg
Reason: tried: /usr/local/opt/libgcrypt/lib/libgcrypt.20.dylib no
such file),
/System/Volumes/ Preboot/Cryptexes/OS/usr/local/opt/libgcrypt/ lib/libgcrypt.20.dylib' (no such file),
/usr/local/opt/libgcrypt/lib/libgcrypt.20.dylib' (no such file),
'/Users/dh/Desktop/buskill-v0.6.0.app/Contents/MacOS/libgcrypt.
20 dylib' (no such file)

**Comment by maltfield** [comment]
Thanks for the report!

Unfortunately, this is a known bug that was fixed in v0.7.0

 * https://github.com/BusKill/buskill-app/issues/71
